# Generated by Django 5.0.6 on 2024-06-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emission',
            options={'permissions': [('can_receive', 'Can receive emission'), ('can_reasign', 'Can reasign emission')]},
        ),
    ]
