# Generated by Django 5.0.6 on 2024-05-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
