# Generated by Django 5.0.6 on 2024-06-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0002_alter_emission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emission',
            options={'permissions': [('can_administrate', 'Can reasign emission')]},
        ),
    ]
