# Generated by Django 5.0.6 on 2024-06-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0003_alter_emission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfile',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
