# Generated by Django 5.0.6 on 2024-06-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0004_emissionfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfile',
            name='name',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
