# Generated by Django 5.0.6 on 2024-06-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0005_emissionfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='batch',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
