# Generated by Django 5.0.6 on 2024-06-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0006_emission_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='detail',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
