# Generated by Django 5.0.6 on 2024-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0009_alter_emission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='language',
            field=models.CharField(default='es', max_length=2),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='name',
            field=models.CharField(default='Sequencer', max_length=255),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='primary_color',
            field=models.CharField(default='#00d1b2', max_length=7),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='secondary_color',
            field=models.CharField(default='#4258ff', max_length=7),
        ),
    ]
