# Generated by Django 5.0.6 on 2024-06-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0010_alter_globalsettings_language_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userdepartment',
            unique_together=set(),
        ),
    ]
