# Generated by Django 5.0.6 on 2024-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0011_alter_sequence_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emission',
            options={},
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='can_administrate',
            field=models.BooleanField(default=False),
        ),
    ]
