name: Docker Image CI

on:
  push:
    branches: [ master ]    
env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true
    -
      name: Configure Tags
      run: |
          TAG=$(git describe --tags --abbrev=7 --always)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Version: $TAG"
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin 
    -
      name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        context: ./sequencer
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{env.IMAGE_TAG}}
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{env.TAG}}
